### ISSUE TITLE
成绩查询和图书续借功能有问

### ISSUE THREAD

**Issue by xu42** [paicha/gxgk-wechat-server#1]
是模拟登录还是学校开放了相关接口或者是学校给了数据库访问权限？

**Comment by paicha** [comment]
都是模拟登陆的。 使用 Beautiful Soup 解析 HTML

**Comment by xu42** [comment]
登录验证码是怎么解决的呢？有相关资料可以参考一下么

**Comment by paicha** [comment]
好玩的是，我发现学校的正方系统有多个登录页面，其中一个页面是没有验证码的，所以只管登录查询。

如果有验证码的话，一个是网上搜索看看有没相关系统漏洞可以钻，不行的话，只能[通过算法去识别验证码](http://drops.wooyun.org/tips/6313)了，必要的话还需要保存用户的 cookie 用于下次登录。

**Comment by xu42** [comment]
如果有保存用户的cookie的需求，一般是用memcache么？
微信里，如何做到用户发送一条信息，而后台接连推送两条？（用户发出查询当前借阅图书请求后，后台先推送“查询中...”之后再推送查询结果）

**Comment by paicha** [comment]
保存 cookie，可以放在任何储存数据的地方，数据库也行，就目前项目而言，我会放在 Redis 缓存里。
多条推送是使用了[客服接口](http://mp.weixin.qq.com/wiki/14/d9be34fe03412c92517da10a5980e7ee.html)，需要服务号并且进行微信认证。

**Comment by xu42** [comment]
你们学校的教务系统和图书馆系统，可以外网访问么？（我学校的图书馆系统外网无法访问，曾经写出来了模拟登录成功了却发现无法外网访问，而向学校网络中心申请服务器又受阻，所幸教务系统可以外网访问）。这点是如何解决的呢？找到了校内可以用于代理的机器么？校内的机器也一般非公网IP的吧？穿透内网是怎么解决的呢？

**Comment by paicha** [comment]
我们学校的教务系统和图书馆系统都可以外网访问，内网也有地址。
我们团队在校内有服务器，搭建 ngrok 解决内网穿透的问题。
当外网查询失败，自动切换内网代理查询。

**Comment by xu42** [comment]
谢谢，我也准备整合我写的几个小功能到校园微信公众号，也通过你的项目知道了WeUI这个前端库，感谢
