### ISSUE TITLE
调试时的问题

### ISSUE THREAD

**Issue by jiansuper** [paicha/gxgk-wechat-server#3]
作者你好，首先非常感谢您分享源码
我的部署环境是VM ubuntu，安装好mysql，redis 和依赖包（无错误）后，走到
# into Python shell

> > > from main.models import db
> > > 这一步时出现错误，错误如下
> > > from main.models import db
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "main/**init**.py", line 12, in <module>
> > >     app.config.from_object('config')
> > >   File "/usr/local/lib/python2.7/dist-packages/flask/config.py", line 162, in from_object
> > >     obj = import_string(obj)
> > >   File "/usr/local/lib/python2.7/dist-packages/werkzeug/utils.py", line 443, in import_string
> > >     sys.exc_info()[2])
> > >   File "/usr/local/lib/python2.7/dist-packages/werkzeug/utils.py", line 418, in import_string
> > >     **import**(import_name)
> > > werkzeug.utils.ImportStringError: import_string() failed for 'config'. Possible reasons are:
- missing **init**.py in a package;
- package or module path not included in sys.path;
- duplicated package or module name taking precedence in sys.path;
- missing module, class, function or variable;

Debugged import:
- 'config' not found.

Original exception:

ImportError: No module named config
希望得到帮助

**Comment by paicha** [comment]
你创建配置文件了吗

**Comment by jiansuper** [comment]
创建了，按照操作步骤一步步做的
@ubuntu:~/wechat$ ls
instance  LICENSE  main  package.json  README.md  requirements.txt  run.py  test
@ubuntu:~/wechat/instance$ ls
config.example  config.py

**Comment by jiansuper** [comment]
不好意思，掉了项目目录下的config.py文件，现在好了

**Comment by jiansuper** [comment]
请问一下nginx文件要怎么配置

**Comment by paicha** [comment]
搜索相关 NGINX 文档，反向代理一下就行了。

jiansuper notifications@github.com于2016年4月23日 周六下午10:19写道：

**Comment by jiansuper** [comment]
谢谢，你好。成功以后用浏览器访问是显示Hello world吗, 但是公众号提交返回请求URL超时，instance / config 文件中的内容都已填上

**Comment by paicha** [comment]
浏览器访问不会显示「Hello World」
具体你要调试，看看是不是 NGINX 配置问题，还是配置文件不正确。

**Comment by lwhile** [comment]
@jiansuper 是广科学生 ?

**Comment by jiansuper** [comment]
不是，学习来的。
@paicha 现测试的服务号可以使用了，但是进入服务号后下面没有菜单

**Comment by paicha** [comment]
回复「更新菜单」

jiansuper notifications@github.com于2016年4月25日周一 上午11:50写道：

**Comment by paicha** [comment]
遇到问题先仔细调试下，看看代码。我先 close 了

**Comment by jiansuper** [comment]
好的，谢谢 
------------------ 原始邮件 ------------------
发件人: "Gary"notifications@github.com
发送时间: 2016年4月25日(星期一) 中午12:41
收件人: "paicha/gxgk-wechat-server"gxgk-wechat-server@noreply.github.com;
抄送: "jiansuper"tzj@hnlh.biz;"Mention"mention@noreply.github.com;
主题: Re: [paicha/gxgk-wechat-server] 调试时的问题 (#3)

遇到问题先仔细调试下，看看代码。我先 close 了

&mdash;
