### ISSUE TITLE
数据库创建

### ISSUE THREAD

**Issue by javaxiu** [paicha/gxgk-wechat-server#5]
我把手动操作的db.create_all()方法放到route里面，写了一个/install的route，再启动服务然后访问localhost/install，调用是成功的，但是数据库表并没有创建起来。这是为什么呢？反之如果python命令行手动create就可以

**Comment by paicha** [comment]
通过 HTTP 请求来初始化数据库是不合理的实现方式。
至于为什么没有创建起来，建议 Google 一下，或翻阅 Flask SQLAlchemy 的源码。
