### ISSUE TITLE
 Python 'tuple' cannot be converted to a MySQL type

### ISSUE THREAD

**Issue by M-Kepler** [paicha/gxgk-wechat-server#7]
冒犯打扰, 我在运行程序的时候发生如下错误: 
sqlalchemy.exc.ProgrammingError: (mysql.connector.errors.ProgrammingError) Failed processing pyformat-parameters; Python 'tuple' cannot be converted to a MySQL type.
我用的是MySQL引擎是: mysql-connetctor-python-rf==2.2.1

**Comment by paicha** [comment]
https://github.com/paicha/gxgk-wechat-server/blob/master/requirements.txt
使用的是 MySQL-python

**Comment by M-Kepler** [comment]
已经解决了,,谢谢答复
